# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bump version
      run: |
        echo ${GITHUB_REF#refs/*/v} > version.txt
    - name: Git commit, rebase onto master
      env:
        PUSH_BRANCH: master
        TMP_BRANCH: ${{ github.repository }}${{ github.run_id}}
      run: |
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --local user.name "$GITHUB_ACTOR"
        git checkout -b $TMP_BRANCH
        git add version.txt
        git commit -m 'Bump version'
        git fetch
        git checkout -b $PUSH_BRANCH --track origin/${PUSH_BRANCH}
        git rebase $TMP_BRANCH $PUSH_BRANCH
        git push
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
